name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
  merge_group:
    types: [checks_requested]

permissions:
  contents: read 

env: 
  MSRV: 1.69.0
  RUSTFLAGS: -Dwarnings

jobs:
  freebsd-firecracker:
    name: freebsd 15 firecracker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Launch Firecracker VM
        uses: acj/freebsd-firecracker-action@v0.9.1
        with:
          run-in-vm: |
            uname -a
            whoami
            kldload mqueuefs
            pkg install -y curl
            fetch https://sh.rustup.rs -o rustup.sh
            sh rustup.sh -y --profile=minimal --default-toolchain stable
            . $HOME/.cargo/env
            rustc -Vv
            rustup target add i686-unknown-freebsd
            rustup component add clippy
            cargo build --all-targets --all-features
            cargo doc --no-deps --all-features
            cargo clippy --all-targets --all-features -- -D warnings -A unknown-lints
            mkdir -p $HOME/.cargo/bin; export PATH=$HOME/.cargo/bin:$PATH
            curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-freebsd.tar.gz | tar xzf - -C ~/.cargo/bin
            cargo hack check --each-feature
            cargo test --all-features
            cargo build --target i686-unknown-freebsd --all-features --all-targets
            cargo doc --no-deps --target i686-unknown-freebsd --all-features
            cargo test --target i686-unknown-freebsd
