name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
  merge_group:
    types: [checks_requested]

jobs:
  freebsd_x86_64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: freebsd
            version: "14.3"
            arch: x86_64
            action: vmactions/freebsd-vm@v1
          - os: freebsd
            version: "15.0"
            arch: x86_64
            action: vmactions/freebsd-vm@v1
          - os: netbsd
            version: "10.1"
            arch: x86_64
            action: vmactions/netbsd-vm@v1
          # Disable FreeBSD/aarch64 because it's too slow
          #- os: freebsd
            #version: "15.0"
            #arch: aarch64
    steps:
      - uses: actions/checkout@v6
      - name: Start VM
        uses: matrix.action
        with:
          release: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          usesh: true
          custom-shell-name: vmsh
      - name: Install dependencies
        if: matrix.arch == 'x86_64' && matrix.os = 'freebsd'
        shell: vmsh {0}
        run: |
          pkg install -y curl
          kldload mqueuefs
          fetch https://sh.rustup.rs -o rustup.sh
          sh rustup.sh -y --profile=minimal --default-toolchain stable
          . $HOME/.cargo/env
          rustc -vV
          rustup component add clippy
      - name: Install dependencies
        if: matrix.arch == 'aarch64' && matrix.os = 'freebsd'
        shell: vmsh {0}
        run: |
          pkg install -y rust
          kldload mqueuefs
          rustc -vV
      - name: Install dependencies
        if: matrix.os = 'netbsd'
        shell: vmsh {0}
        run: |
          pkg_add curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo '. $HOME/.cargo/env' >> $HOME/.profile
      - name: Build
        shell: vmsh {0}
        run: |
          echo PWD is $PWD
          echo GITHUB_WORKSPACE is $GITHUB_WORKSPACE
          echo GITHUB_ENV is $GITHUB_ENV
          echo GITHUB_PATH is $GITHUB_PATH
          echo GITHUB_PATH contains `cat $GITHUB_PATH`
          echo PATH is $PATH
          ls
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo build --all-targets --all-features
      - name: Test
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo test --all-targets --all-features
      - name: Clippy
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo clippy --all-targets --all-features -- -D warnings -A unknown-lints
      - name: Doc
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo doc --no-deps --all-features
      - name: Hack
        if: matrix.arch == 'x86_64'
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          mkdir -p $HOME/.cargo/bin; export PATH=$HOME/.cargo/bin:$PATH
          curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-freebsd.tar.gz | tar xzf - -C ~/.cargo/bin
          cargo hack check --each-feature
      - name: i686 Build
        if: matrix.arch == 'aarch64' && matrix.os = 'freebsd'
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          rustup target add i686-unknown-freebsd
          cargo build --target i686-unknown-freebsd --all-features --all-targets
      - name: i686 Test
        if: matrix.arch == 'aarch64' && matrix.os = 'freebsd'
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo test --all-targets --all-features --target i686-unknown-freebsd 
      - name: i686 Doc
        if: matrix.arch == 'aarch64' && matrix.os = 'freebsd'
        shell: vmsh {0}
        run: |
          if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
          cargo doc --no-deps --all-features --target i686-unknown-freebsd 

  # Each operating system needs a separate job.  They can't share job
  # configurations due to https://github.com/vmactions/netbsd-vm/issues/7
  #netbsd:
    #runs-on: ubuntu-latest
    #name: NetBSD
    #steps:
      #- uses: actions/checkout@v6
      #- name: Start VM
        #uses: vmactions/netbsd-vm@v1
        #with:
          #release: "10.1"
          #usesh: true
      #- name: Install dependencies
        #shell: netbsd {0}
        #run: |
          #pkg_add curl
          #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          #echo '. $HOME/.cargo/env' >> $HOME/.profile
      #- name: build
        #uses: ./.github/actions/build
        #with:
          #SHELL: "netbsd {0}"
          #TARGET: x86_64-unknown-netbsd
          #NOHACK: true
      #- name: test
        #uses: ./.github/actions/test
        #with:
          #SHELL: "netbsd {0}"
          #TARGET: x86_64-unknown-netbsd
          #NOHACK: true
          #SUDO: ""
        #shell: netbsd {0}
        #run: |
          #cargo build --all-targets --all-features
      #- name: Test
        #shell: netbsd {0}
        #run: |
          #cargo test --all-targets --all-features
      #- name: Clippy
        #shell: netbsd {0}
        #run: |
          #cargo clippy --all-targets --all-features -- -D warnings -A unknown-lints
      #- name: Doc
        #shell: netbsd {0}
        #run: |
          #cargo doc --no-deps --all-features

  #openbsd:
    #runs-on: ubuntu-latest
    #name: OpenBSD
    #steps:
      #- uses: actions/checkout@v6
      #- name: Start VM
        #uses: vmactions/openbsd-vm@v1
        #with:
          #release: "7.8"
          #usesh: true
      #- name: Install dependencies
        #shell: openbsd {0}
        #run: |
          #pkg_add rust
          #rustc -Vv
      #- name: Build
        #shell: openbsd {0}
        #run: |
          #cargo build --all-targets --all-features
      #- name: Test
        #shell: openbsd {0}
        #run: |
          #cargo test --all-targets --all-features
      #- name: Doc
        #shell: openbsd {0}
        #run: |
          #cargo doc --no-deps --all-features

  #haiku:
    #runs-on: ubuntu-latest
    #name: Haiku
    #steps:
      #- uses: actions/checkout@v6
      #- name: Start VM
        #uses: vmactions/haiku-vm@v1
        #with:
          #release: "r1beta5"
          #usesh: true
      #- name: Install dependencies
        #shell: haiku {0}
        #run: |
          #pkgman install -y rust_bin
          #rustc -Vv
      #- name: Build
        #shell: haiku {0}
        #run: |
          #cargo build --all-targets --all-features
      #- name: Test
        #shell: haiku {0}
        #run: |
          #cargo test --all-targets --all-features
      #- name: Doc
        #shell: haiku {0}
        #run: |
          #cargo doc --no-deps --all-features

  #omnios:
    #runs-on: ubuntu-latest
    #name: OmniOS
    #steps:
      #- uses: actions/checkout@v6
      #- name: Start VM
        #uses: vmactions/omnios-vm@v1
        #with:
          #release: "r151056"
          #usesh: true
      #- name: Install dependencies
        #shell: omnios {0}
        #run: |
          #pkg install developer/build-essential
          #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      #- name: Build
        #shell: omnios {0}
        #run: |
          #. $HOME/.cargo/env
          #cargo build --all-targets --all-features
      #- name: Test
        #shell: omnios {0}
        #run: |
          #. $HOME/.cargo/env
          #cargo test --all-targets --all-features
      #- name: Clippy
        #shell: omnios {0}
        #run: |
          #. $HOME/.cargo/env
          #cargo clippy --all-targets --all-features -- -D warnings -A unknown-lints
      #- name: Doc
        #shell: omnios {0}
        #run: |
          #. $HOME/.cargo/env
          #cargo doc --no-deps --all-features

