name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
  merge_group:
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ${{ matrix.os.name }}-${{ matrix.os.version}}/${{ matrix.os.architecture }}
        uses: cross-platform-actions/action@v1.0.0
        with:
          operating_system: freebsd
          version: 15.0
          run: |
            uname -a
            kldload mqueuefs
            fetch https://sh.rustup.rs -o rustup.sh
            sh rustup.sh -y --profile=minimal --default-toolchain stable
            . $HOME/.cargo/env
            rustc -Vv
            rustup target add i686-unknown-freebsd
            rustup component add clippy
            cargo build --all-targets --all-features
            cargo doc --no-deps --all-features
            cargo clippy --all-targets --all-features -- -D warnings -A unknown-lints
            cargo test --all-features
            rm -rf $CARGO_HOME/registry/index
